/*
==============================================================

File : ICustomerDrawingService.cs

Purpose :
Defines Customer Drawing business operations.

Final Design :
- Customer Drawing follows Drawing Master revision workflow.
- One Customer + One Item = One Customer Drawing Number.
- Drawing Number is permanent.
- First Revision is system generated as RV-01.
- New Revision Numbers are automatically generated.
- Existing revisions are never overwritten.
- Only one revision can be Current.
- Previous revisions may be Activated.
- Historical revisions may be Soft Deleted.
- Complete Customer Drawing may be Soft Deleted / Restored.
- Deleted Revision Numbers are never reused.

Important :
- Customer is part of Customer Drawing identity.
- Same Drawing Number may exist for different Customers.
- Same Item may have separate Customer Drawings
  for different Customers.
- Existing Drawing Master remains completely separate.

==============================================================
*/

using AjayIndustriesERP.Application.Common;
using AjayIndustriesERP.Domain.Entities;

namespace AjayIndustriesERP.Application.Interfaces
{
    public interface ICustomerDrawingService
    {
        #region Read

        Task<List<CustomerDrawing>>
            GetAllAsync();


        Task<CustomerDrawing?>
            GetByIdAsync(
                int customerDrawingId);


        /*
         * Used later by Customer PO / Production.
         *
         * Returns only the Current Customer Drawing
         * for selected Customer + Item.
         */
        Task<CustomerDrawing?>
            GetByCustomerAndItemAsync(
                int customerId,
                int itemId);


        Task<List<CustomerDrawing>>
            SearchAsync(
                string searchText);


        Task<PagedResult<CustomerDrawing>>
            GetPagedAsync(
                int pageNumber,
                int pageSize);

        #endregion


        #region Revision History

        /*
         * customerDrawingId may belong to either
         * Current or historical revision.
         *
         * Service resolves:
         *
         * CustomerId + DrawingNumber
         *
         * and returns complete active revision history.
         */
        Task<List<CustomerDrawing>>
            GetRevisionHistoryAsync(
                int customerDrawingId);

        #endregion


        #region Create

        /*
         * Creates a new Customer Drawing.
         *
         * Service automatically creates:
         *
         * RevisionNumber = RV-01
         * IsActive = true
         */
        Task CreateAsync(
            CustomerDrawing customerDrawing);

        #endregion


        #region Update / Add Revision

        /*
         * Updates Drawing-level information and
         * optionally creates new revision rows.
         *
         * Existing revision rows are never overwritten.
         *
         * Revision Numbers for newRevisions are
         * generated by Service.
         */
        Task UpdateAsync(
            CustomerDrawing customerDrawing,
            IEnumerable<CustomerDrawing>
                newRevisions);

        #endregion


        #region Activate Revision

        /*
         * Makes selected historical revision Current.
         *
         * Previous Current revision becomes inactive.
         */
        Task ActivateRevisionAsync(
            int customerDrawingId);

        #endregion


        #region Delete Revision

        /*
         * Soft deletes one historical revision.
         *
         * Current revision cannot be deleted
         * through this operation.
         */
        Task DeleteRevisionAsync(
            int customerDrawingId);

        #endregion


        #region Delete Complete Customer Drawing

        /*
         * Soft deletes complete revision history
         * belonging to:
         *
         * CustomerId + DrawingNumber
         */
        Task DeleteAsync(
            int customerDrawingId);

        #endregion


        #region Deleted / Restore

        /*
         * Returns one representative row for each
         * completely deleted Customer Drawing.
         */
        Task<List<CustomerDrawing>>
            GetDeletedDrawingsAsync();


        /*
         * Restores complete Customer Drawing
         * revision history.
         *
         * Last Current revision is restored as Current.
         */
        Task RestoreAsync(
            int customerDrawingId);

        #endregion
    }
}