/*
============================================================
File: ICustomerDrawingService.cs

Purpose:
Defines Customer Drawing application business operations.

Responsibilities:
- Retrieve current Customer Drawings.
- Retrieve Customer Drawing by Customer + Item.
- Retrieve exact historical Customer Drawing revision.
- Search and paginate Customer Drawings.
- Retrieve revision history.
- Create first revision.
- Add new revisions.
- Activate historical revision.
- Delete inactive revision.
- Soft-delete complete Customer Drawing.
- Restore deleted Customer Drawing.

Important:
- Customer Drawing identity is Customer + Drawing Number.
- One Customer + One Item has one current Customer Drawing.
- Revision numbers are generated by Application Service.
- Revision numbers are never reused.
- Exact revision lookup supports historical transaction
  snapshots such as Customer Purchase Orders.
============================================================
*/

using AjayIndustriesERP.Application.Common;
using AjayIndustriesERP.Domain.Entities;

namespace AjayIndustriesERP.Application.Interfaces
{
    public interface ICustomerDrawingService
    {
        #region Read Operations

        Task<List<CustomerDrawing>>
            GetAllAsync();


        Task<CustomerDrawing?>
            GetByIdAsync(
                int customerDrawingId);


        Task<CustomerDrawing?>
            GetByCustomerAndItemAsync(
                int customerId,
                int itemId);


        /*
         * Returns the exact revision belonging to:
         *
         * Customer + Drawing Number + Revision Number.
         *
         * Used by historical transactions such as
         * Customer Purchase Order Details.
         */
        Task<CustomerDrawing?>
            GetRevisionAsync(
                int customerId,
                string drawingNumber,
                string revisionNumber);


        Task<List<CustomerDrawing>>
            SearchAsync(
                string searchText);


        Task<PagedResult<CustomerDrawing>>
            GetPagedAsync(
                int pageNumber,
                int pageSize);

        #endregion


        #region Revision History

        Task<List<CustomerDrawing>>
            GetRevisionHistoryAsync(
                int customerDrawingId);

        #endregion


        Task CreateAsync(
    CustomerDrawing customerDrawing);

        Task UpdateAsync(
            CustomerDrawing customerDrawing,
            IEnumerable<CustomerDrawing> newRevisions);


        #region Revision Workflow

        Task ActivateRevisionAsync(
            int customerDrawingId);


        Task DeleteRevisionAsync(
            int customerDrawingId);

        #endregion


        #region Complete Drawing Delete

        Task DeleteAsync(
            int customerDrawingId);

        #endregion


        #region Deleted / Restore

        Task<List<CustomerDrawing>>
            GetDeletedDrawingsAsync();


        Task RestoreAsync(
            int customerDrawingId);

        #endregion
    }
}