/*
============================================================
File: ProductionOperationFormViewModel.cs

Purpose:
Provides Production Operation Master data to Create and Edit forms.

Responsibilities:
- Accept Operation Name.
- Accept Operation Type.
- Accept optional Description.
- Accept optional Remarks.
- Provide Web-level validation.
- Support both Create and Edit using reusable _Form.cshtml.

Important:
- Operation Code is generated by ProductionOperationService.
- Business validation remains in Application Service.
- Setup Time, Cycle Time and Machine assignment do NOT belong
  to Operation Master.
============================================================
*/

using AjayIndustriesERP.Domain.Enums;
using System.ComponentModel.DataAnnotations;

namespace AjayIndustriesERP.Web.ViewModels.ProductionOperation
{
    public class ProductionOperationFormViewModel
    {
        #region Identification

        public int Id { get; set; }


        [Display(Name = "Operation Code")]
        public string? Code { get; set; }

        #endregion


        #region Operation Information

        [Required(
            ErrorMessage = "Operation Name is required.")]
        [StringLength(
            150,
            ErrorMessage = "Operation Name cannot exceed 150 characters.")]
        [Display(Name = "Operation Name")]
        public string OperationName { get; set; } =
            string.Empty;


        [Required(
            ErrorMessage = "Operation Type is required.")]
        [Display(Name = "Operation Type")]
        public ProductionOperationType OperationType { get; set; } =
            ProductionOperationType.Production;


        [StringLength(
            500,
            ErrorMessage = "Description cannot exceed 500 characters.")]
        public string? Description { get; set; }

        #endregion


        #region Remarks

        [StringLength(
            1000,
            ErrorMessage = "Remarks cannot exceed 1000 characters.")]
        public string? Remarks { get; set; }

        #endregion
    }
}