<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="QuestPDF" Version="2026.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AjayIndustriesERP.Domain\AjayIndustriesERP.Domain.csproj" />
  </ItemGroup>

</Project>
