/*
============================================================
File: CustomerPurchaseOrder.cs

Purpose:
Represents a Purchase Order received from a Customer.

Responsibilities:
- Store the internal ERP Customer PO number.
- Reference the Customer Master.
- Store the Customer's original Purchase Order number.
- Store Customer PO dates and required delivery date.
- Store Customer PO business priority.
- Store Customer PO transaction status.
- Store Customer identity snapshot for historical accuracy.
- Own all Customer Purchase Order Items.
- Act as the source transaction for future Production Jobs,
  Production Pipelines, Dispatch and Sales Invoice workflows.

Important:
- Internal Customer PO Code is generated by Application Service.
- Customer Purchase Order Number is supplied by the Customer.
- Same Customer + Same Customer PO Number must not be duplicated.
- CustomerName is stored as a snapshot.
- Production Machine / Current Step / Pipeline Status must NOT
  be stored directly in this entity.
- Production tracking will later be linked through:
      CustomerPurchaseOrderItem
          → ProductionJob
          → ProductionJobStep
============================================================
*/

using AjayIndustriesERP.Domain.Common;
using AjayIndustriesERP.Domain.Enums;

namespace AjayIndustriesERP.Domain.Entities
{
    public class CustomerPurchaseOrder : BaseEntity
    {
        #region Primary Identification

        public int Id { get; set; }

        /// <summary>
        /// Internal ERP generated Customer PO code.
        /// Example: AI/CPO/26-27/00001
        /// </summary>
        public string Code { get; set; } = string.Empty;

        #endregion


        #region Customer Reference

        public int CustomerId { get; set; }

        public Customer Customer { get; set; } = null!;


        /// <summary>
        /// Snapshot of Customer Name at the time the PO is created.
        /// </summary>
        public string CustomerName { get; set; } = string.Empty;

        #endregion


        #region Customer Purchase Order Information

        /// <summary>
        /// Purchase Order number supplied by the Customer.
        /// </summary>
        public string CustomerPurchaseOrderNumber { get; set; } =
            string.Empty;


        /// <summary>
        /// Date printed / issued on the Customer's Purchase Order.
        /// </summary>
        public DateTime CustomerPurchaseOrderDate { get; set; }


        /// <summary>
        /// Date on which Ajay Industries received the Customer PO.
        /// </summary>
        public DateTime ReceivedDate { get; set; }


        /// <summary>
        /// Overall required delivery date for the Customer PO.
        /// Individual PO Items may optionally override this date.
        /// </summary>
        public DateTime RequiredDeliveryDate { get; set; }

        #endregion


        #region Priority

        public CustomerPurchaseOrderPriority Priority { get; set; } =
            CustomerPurchaseOrderPriority.Normal;

        #endregion


        #region Status

        public CustomerPurchaseOrderStatus Status { get; set; } = CustomerPurchaseOrderStatus.Draft;

        #endregion


        #region Customer Reference Information

        /// <summary>
        /// Optional additional reference supplied by the Customer.
        /// </summary>
        public string? CustomerReference { get; set; }

        #endregion


        #region Remarks

        public string? Remarks { get; set; }

        #endregion


        #region Purchase Order Items

        public ICollection<CustomerPurchaseOrderItem> Items { get; set; } =
            new List<CustomerPurchaseOrderItem>();

        #endregion
    }
}