/*
============================================================
File: Customer.cs

Purpose:
Represents a customer registered in Ajay Industries ERP.

Responsibilities:
- Store the customer's internal ERP code.
- Store customer identity and legal information.
- Store GST / PAN information.
- Store primary contact details.
- Store the primary customer address.
- Store payment-related master information.
- Act as the parent master for future Customer Purchase Orders,
  Production Jobs, Dispatches and Sales Invoices.

Important:
- Customer Code is generated by the Application Service.
- GSTIN is optional.
- Phase 1 supports one primary contact and one primary address.
- Multiple addresses / contacts may be introduced later when
  Dispatch and Sales Invoice workflows require them.
- Credit Limit is intentionally not part of Phase 1.
============================================================
*/

using AjayIndustriesERP.Domain.Common;

namespace AjayIndustriesERP.Domain.Entities
{
    public class Customer : BaseEntity
    {
        public int Id { get; set; }


        // ====================================================
        // INTERNAL ERP IDENTIFICATION
        // ====================================================

        public string Code { get; set; } = string.Empty;


        // ====================================================
        // CUSTOMER INFORMATION
        // ====================================================

        public string CustomerName { get; set; } = string.Empty;

        public string? LegalName { get; set; }


        // ====================================================
        // TAX INFORMATION
        // ====================================================

        public string? GSTIN { get; set; }

        public string? PAN { get; set; }


        // ====================================================
        // PRIMARY CONTACT
        // ====================================================

        public string? ContactPerson { get; set; }

        public string? MobileNumber { get; set; }

        public string? AlternateMobileNumber { get; set; }

        public string? Email { get; set; }


        // ====================================================
        // PRIMARY ADDRESS
        // ====================================================

        public string AddressLine1 { get; set; } = string.Empty;

        public string? AddressLine2 { get; set; }

        public string City { get; set; } = string.Empty;

        public string? District { get; set; }

        public string State { get; set; } = string.Empty;

        public string Pincode { get; set; } = string.Empty;

        public string Country { get; set; } = "India";


        // ====================================================
        // COMMERCIAL INFORMATION
        // ====================================================

        public string? PaymentTerms { get; set; }

        public int? CreditDays { get; set; }


        // ====================================================
        // OTHER INFORMATION
        // ====================================================

        public string? Website { get; set; }

        public string? Remarks { get; set; }
    }
}