/*
============================================================
File: CustomerPurchaseOrderItem.cs

Purpose:
Represents one Item ordered within a Customer Purchase Order.

Responsibilities:
- Reference the parent Customer Purchase Order.
- Reference the existing Item Master.
- Store Item Master snapshots for historical accuracy.
- Store Customer-specific Item / Drawing references.
- Store Ordered Quantity.
- Allow line-level Delivery Date override.
- Allow line-level Priority override.
- Act as the future source for Production Job creation.

Important:
- ItemId references the existing ERP Item Master.
- Item data is NOT manually duplicated as another Product Master.
- ItemCode / ItemName / Specification / UnitName are snapshots.
- If Item Master changes later, historical Customer PO remains
  unchanged.
- RequiredDeliveryDate is optional:
      null = use Customer PO header RequiredDeliveryDate.
- Priority is optional:
      null = use Customer PO header Priority.
- Production Machine / Production Status is not stored here.
  Future relationship:
      CustomerPurchaseOrderItem
          → ProductionJob
          → ProductionJobStep
============================================================
*/

using AjayIndustriesERP.Domain.Common;
using AjayIndustriesERP.Domain.Enums;

namespace AjayIndustriesERP.Domain.Entities
{
    public class CustomerPurchaseOrderItem : BaseEntity
    {
        #region Primary Identification

        public int Id { get; set; }


        /// <summary>
        /// Internal line code generated by Application Service.
        /// </summary>
        public string Code { get; set; } = string.Empty;

        #endregion


        #region Customer Purchase Order Reference

        public int CustomerPurchaseOrderId { get; set; }

        public CustomerPurchaseOrder CustomerPurchaseOrder { get; set; } =
            null!;

        #endregion


        #region Item Master Reference

        public int ItemId { get; set; }

        public Item Item { get; set; } = null!;

        #endregion


        #region Item Snapshot

        /// <summary>
        /// Item Code snapshot from Item Master.
        /// </summary>
        public string ItemCode { get; set; } = string.Empty;


        /// <summary>
        /// Item Name snapshot from Item Master.
        /// </summary>
        public string ItemName { get; set; } = string.Empty;


        /// <summary>
        /// Item Specification snapshot from Item Master.
        /// </summary>
        public string? Specification { get; set; }


        /// <summary>
        /// Unit Name snapshot from Item Master.
        /// </summary>
        public string UnitName { get; set; } = string.Empty;

        #endregion


        #region Customer Item Reference

        /// <summary>
        /// Customer's own Item / Part Code if provided.
        /// </summary>
        public string? CustomerItemCode { get; set; }


        /// <summary>
        /// Customer supplied Drawing Number if provided.
        /// This is separate from Ajay Industries internal
        /// Drawing Information stored against Item Master.
        /// </summary>
        public string? CustomerDrawingNumber { get; set; }


        /// <summary>
        /// Customer Drawing / Part Revision.
        /// Example: R1, R2, Rev-A.
        /// </summary>
        public string? Revision { get; set; }

        #endregion


        #region Ordered Quantity

        public decimal OrderedQuantity { get; set; }

        #endregion


        #region Delivery Date Override

        /// <summary>
        /// Optional line-level delivery date.
        /// When null, use CustomerPurchaseOrder.RequiredDeliveryDate.
        /// </summary>
        public DateTime? RequiredDeliveryDate { get; set; }

        #endregion


        #region Priority Override

        /// <summary>
        /// Optional line-level priority.
        /// When null, use CustomerPurchaseOrder.Priority.
        /// </summary>
        public CustomerPurchaseOrderPriority? Priority { get; set; }

        #endregion


        #region Remarks

        public string? Remarks { get; set; }

        #endregion
    }
}