/*
============================================================
File: CustomerConfiguration.cs

Purpose:
Configures the Customer entity for Entity Framework Core.

Responsibilities:
- Map Customer to the Customers table.
- Configure required fields and maximum lengths.
- Configure unique Customer Code.
- Prevent duplicate GSTIN values when GSTIN is provided.
- Keep all Customer database mapping outside DbContext.

Important:
- GSTIN is optional.
- Customer Code is generated by the Application Service.
- Customer Name is not unique because different customers may
  legitimately have similar or identical display names.
============================================================
*/

using AjayIndustriesERP.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AjayIndustriesERP.Infrastructure.Configurations
{
    public class CustomerConfiguration
        : IEntityTypeConfiguration<Customer>
    {
        public void Configure(
            EntityTypeBuilder<Customer> builder)
        {
            // =================================================
            // TABLE
            // =================================================

            builder.ToTable("Customers");


            // =================================================
            // PRIMARY KEY
            // =================================================

            builder.HasKey(x => x.Id);


            // =================================================
            // CUSTOMER CODE
            // =================================================

            builder.Property(x => x.Code)
                .IsRequired()
                .HasMaxLength(50);

            builder.HasIndex(x => x.Code)
                .IsUnique();


            // =================================================
            // CUSTOMER INFORMATION
            // =================================================

            builder.Property(x => x.CustomerName)
                .IsRequired()
                .HasMaxLength(200);

            builder.Property(x => x.LegalName)
                .HasMaxLength(250);


            // =================================================
            // TAX INFORMATION
            // =================================================

            builder.Property(x => x.GSTIN)
                .HasMaxLength(15);

            builder.Property(x => x.PAN)
                .HasMaxLength(10);

            builder.HasIndex(x => x.GSTIN)
    .IsUnique()
    .HasFilter(
        "[GSTIN] IS NOT NULL AND [IsDeleted] = 0");


            // =================================================
            // PRIMARY CONTACT
            // =================================================

            builder.Property(x => x.ContactPerson)
                .HasMaxLength(150);

            builder.Property(x => x.MobileNumber)
                .HasMaxLength(20);

            builder.Property(x => x.AlternateMobileNumber)
                .HasMaxLength(20);

            builder.Property(x => x.Email)
                .HasMaxLength(200);

            builder.HasIndex(x => x.Email)
    .IsUnique()
    .HasFilter(
        "[Email] IS NOT NULL AND [IsDeleted] = 0");


            builder.HasIndex(x => x.MobileNumber)
                .IsUnique()
                .HasFilter(
                    "[MobileNumber] IS NOT NULL AND [IsDeleted] = 0");


            builder.HasIndex(x => x.AlternateMobileNumber)
                .IsUnique()
                .HasFilter(
                    "[AlternateMobileNumber] IS NOT NULL AND [IsDeleted] = 0");

            // =================================================
            // PRIMARY ADDRESS
            // =================================================

            builder.Property(x => x.AddressLine1)
                .IsRequired()
                .HasMaxLength(250);

            builder.Property(x => x.AddressLine2)
                .HasMaxLength(250);

            builder.Property(x => x.City)
                .IsRequired()
                .HasMaxLength(100);

            builder.Property(x => x.District)
                .HasMaxLength(100);

            builder.Property(x => x.State)
                .IsRequired()
                .HasMaxLength(100);

            builder.Property(x => x.Pincode)
                .IsRequired()
                .HasMaxLength(10);

            builder.Property(x => x.Country)
                .IsRequired()
                .HasMaxLength(100)
                .HasDefaultValue("India");


            // =================================================
            // COMMERCIAL INFORMATION
            // =================================================

            builder.Property(x => x.PaymentTerms)
                .HasMaxLength(250);


            // =================================================
            // OTHER INFORMATION
            // =================================================

            builder.Property(x => x.Website)
                .HasMaxLength(250);

            builder.Property(x => x.Remarks)
                .HasMaxLength(1000);


            // =================================================
            // COMMON QUERY INDEXES
            // =================================================

            builder.HasIndex(x => x.CustomerName);

            builder.HasIndex(x => x.State);

            builder.HasIndex(x => x.IsActive);

            builder.HasIndex(x => x.IsDeleted);
        }
    }
}